import { StyleSheet } from "react-native";

export const C = {
  bg: "#f3f4f6",
  surface: "#ffffff",
  primary: "#fe424d",
  primaryDark: "#dc2626",
  text: "#111827",
  textSub: "#4b5563",
  textLabel: "#374151",
  textMuted: "#6b7280",
  border: "#d1d5db",
  inputBg: "#f9fafb",
  errorBg: "#fef2f2",
  errorBorder: "#fee2e2",
  errorText: "#dc2626",
  successBg: "#f0fdf4",
  successBorder: "#dcfce7",
  successText: "#059669",
  dividerLine: "#e5e7eb",
  dividerText: "#9ca3af",
  googleBorder: "#d1d5db",
  googleText: "#374151",
  linkText: "#fe424d",
  switchText: "#4b5563",
  forgotText: "#4b5563",
};

export const authStyles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: C.bg,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: "center",
    padding: 20,
  },
  langRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginBottom: 16,
  },
  langBtn: {
    paddingHorizontal: 14,
    paddingVertical: 5,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.surface,
  },
  langBtnText: {
    fontSize: 12,
    fontWeight: "700",
    color: C.text,
  },
  card: {
    backgroundColor: C.surface,
    borderRadius: 16,
    padding: 32,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.05,
    shadowRadius: 25,
    elevation: 4,
  },
  title: {
    fontSize: 28,
    fontWeight: "800",
    color: C.text,
    textAlign: "center",
    marginBottom: 0,
  },
  subtitle: {
    fontSize: 15,
    color: C.textSub,
    textAlign: "center",
    lineHeight: 22,
    marginTop: 10,
    marginBottom: 24,
  },
  errorBox: {
    backgroundColor: C.errorBg,
    borderWidth: 1,
    borderColor: C.errorBorder,
    borderRadius: 10,
    padding: 12,
    marginBottom: 16,
    alignItems: "center",
  },
  errorText: {
    color: C.errorText,
    fontSize: 14,
    textAlign: "center",
  },
  successBox: {
    backgroundColor: C.successBg,
    borderWidth: 1,
    borderColor: C.successBorder,
    borderRadius: 10,
    paddingVertical: 14,
    paddingHorizontal: 18,
    marginBottom: 16,
    alignItems: "center",
  },
  successText: {
    color: C.successText,
    fontSize: 14,
    fontWeight: "500",
    textAlign: "center",
  },
  formGroup: {
    marginBottom: 16,
  },
  label: {
    fontSize: 13,
    fontWeight: "600",
    color: C.textLabel,
    marginBottom: 8,
  },
  input: {
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 15,
    color: C.text,
    backgroundColor: C.inputBg,
  },
  otpInput: {
    textAlign: "center",
    fontSize: 26,
    letterSpacing: 12,
    fontFamily: "monospace",
    paddingLeft: 20,
  },
  forgotRow: {
    alignItems: "flex-end",
    marginTop: -8,
    marginBottom: 4,
  },
  forgotText: {
    fontSize: 13,
    fontWeight: "500",
    color: C.forgotText,
  },
  submitBtn: {
    backgroundColor: C.primary,
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: "center",
    marginTop: 8,
  },
  submitBtnDisabled: {
    opacity: 0.7,
  },
  submitBtnText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "700",
  },
  dividerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 22,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: C.dividerLine,
  },
  dividerText: {
    color: C.dividerText,
    fontSize: 11,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 1,
    paddingHorizontal: 14,
  },
  googleBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    borderWidth: 1,
    borderColor: C.googleBorder,
    borderRadius: 10,
    paddingVertical: 12,
    backgroundColor: C.surface,
  },
  googleIcon: {
    width: 20,
    height: 20,
  },
  googleBtnText: {
    color: C.googleText,
    fontSize: 15,
    fontWeight: "600",
  },
  switchRow: {
    flexDirection: "row",
    justifyContent: "center",
    flexWrap: "wrap",
    gap: 4,
    marginTop: 22,
  },
  switchText: {
    color: C.switchText,
    fontSize: 14,
  },
  switchLink: {
    color: C.linkText,
    fontSize: 14,
    fontWeight: "700",
  },
  backBtn: {
    alignItems: "center",
    marginTop: 14,
    paddingVertical: 4,
  },
  backBtnText: {
    color: C.primary,
    fontSize: 14,
    fontWeight: "700",
  },
  resendRow: {
    alignItems: "center",
    marginTop: 14,
  },
  resendText: {
    fontSize: 13,
    color: C.textMuted,
  },
  resendBtn: {
    fontSize: 13,
    color: C.primary,
    fontWeight: "600",
  },
});
